# Basic Settings
title: My Portfolio
description: Explore my projects and contributions
baseurl: "/"

# Theme Settings
theme: jekyll-theme-minimal
  name: portfolio_theme
  # You can specify additional theme-specific settings here

# Layouts
layouts:
  home: /layouts/home.html
  page: /layouts/page.html
  project: /layouts/project.html

# Permalinks
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# GitHub Pages Settings
remote_theme: owner/repo # You can specify a remote theme hosted on GitHub
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

# Author Information
author:
  name: Your Name
  bio: Software Developer | Data Scientist
  location: Your Location
  email: your.email@example.com
  github: yourusername
  linkedin: yourlinkedin
  twitter: yourtwitter

# Navigation
navbar:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: About
    url: /about
